global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

rule_files:
  - '/etc/prometheus/rules/*.yml'

alerting:
  alertmanagers:
  {%- if salt['pillar.get']('prometheus:external_hostname') %}
  - scheme: https
    path_prefix: /alertmanager/
    static_configs:
    - targets: [{{ pillar['prometheus']['external_hostname'].replace('https://', '') }}]
  {%- else %}
  - scheme: http
    static_configs:
    - targets: ["[::1]:9093"]
  {%- endif %}

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ["127.0.0.1:80"]

  - job_name: 'netdata'

    metrics_path: /api/v1/allmetrics
    params:
      format: [ prometheus_all_hosts ]

    static_configs:
      - targets: ['localhost:19999']

{%- for exporter, port in salt['pillar.get']('prometheus:exporter_types') %}
  - job_name: {{ exporter }}
    static_configs:
      - targets:
{%- for salt_minion, exporters in salt['mine.get']('*', 'prometheus.exporters').items() if exporter in exporters %}
{%- set hostname = salt['mine.get'](salt_minion, 'prometheus.hostname').get(salt_minion) %}
        - '{{ hostname }}:{{ port }}'
{%- endfor %}
{%- for target in salt['pillar.get']('prometheus:targets') if target['type'] == exporter %}
        - '{{ target['host'] }}:{{ port }}'
{%- endfor %}
{%- endfor %}


{% for scrape_config in salt['pillar.get']('monitoring:prometheus:scrape_configs', []) %}
  - {{ scrape_config | yaml }}
{% endfor %}
