# listening socket
host: "::1"
port: 28530

geo:
  provider: "mozilla"
  mozilla:
    api_key: "test"


director:
  sqlite_path: "/var/lib/director/director.db"
  geojson: "/etc/domain-director/domains.geojson"
  default_domain: ffka_default
  update_interval: 1800
  meshviewer_json_url: "https://api.karlsruhe.freifunk.net/yanic/meshviewer/meshviewer.json"
  domain_switch_time: -1
  only_migrate_vpn: true
  tolerance_distance: 200
  max_accuracy: 100
